### ISSUE TITLE
Swing hand causes incompatibility with Reliquary, and its config option missing

### ISSUE THREAD

**Issue by Kevun1** [SoraZodia/Survival-Tweaks#17]
Forge v2556
Survival Tweaks v5.0.3

Including Survival Tweaks makes certain items from [Reliquary](https://minecraft.curseforge.com/projects/reliquary-v1-3?gameCategorySlug=mc-mods&projectID=241319) not function. So far, I've found that the Sojourner's Staff, Glacial Staff, Ender Staff, Ice Magus Rod, and Pyromancer's staff don't function as they should on right click. 

I believe (though I am not sure) that the culprit is within Survival Tweak's RightClickItem event handler, which seems to make the player swing their arm on using an item. However, it looks like some of Reliquary's items fail if the player is already swinging their arm ([example](https://github.com/P3pp3rF1y/Reliquary/blob/1.12.x/src/main/java/xreliquary/items/ItemIceMagusRod.java)). It looks like there should be a config option but it doesn't appear in my config options.

I took a pretty cursory glance at the code, so I can't say for sure that's the culprit, but I can't disable it in the config to check because the option isn't there.

edit: it looks like the latest version with the config option simply isn't released yet. So once it is I feel like this issue would be resolved

**Comment by SoraZodia** [comment]
Swing hand is something that should only affect the player graphics-wise,
I'm a bit doubtful that it's what's causing the trouble. Config-wise, that
option is coming in the next update.

It might be something to do with my block-placement code, which would also
be strange since it would only do that if there's an block next to that
item or if interacting with something. I'll go check it out though.

**Comment by SoraZodia** [comment]
I stand corrected, the hand swing (specially [this line](https://github.com/SoraZodia/Survival-Tweaks/blob/9358b9e51d469811d3c6c79543483ea79ebb10d1/src/main/java/sorazodia/survival/mechanics/PlayerActionEvent.java#L106)) was the culprit. 

 I think I'll just remove that part from the mod instead of giving it an config option, the player's swingInProcess variable was something I overlooked when I had put that in.

**Comment by SoraZodia** [comment]
Should be fixed now in v5.0.4
