### ISSUE TITLE
Configurable Parachuting and Miscellaneous Issues

### ISSUE THREAD

**Issue by DarianLStephens** [SoraZodia/Survival-Tweaks#7]
Perhaps you could backport the parachute feature and allow users to specify items which act as parachutes? I know I for one would love to have support for the Crystal Wing or Mine and Blade's shields, but then I'm not sure if M&B's shields are quite... parachute-y enough. You'd probably also need special code to support it's offhand feature, so that might end up being a no.

After a little experimentation, I seem to be throwing two arrows at once, rather than just one. There's also the issue of it not supporting modded arrow types, but I don't know if you can help that.

Also, I'm not sure if this is entirely intentional or even preventable, but if you mine Netherrack/Quartz slowly and carefully, the lava will disappear within seconds instead of spreading out. It's actually kinda neat to need to change up how I mine, and I've proven to myself that accidents still happen if you get careless. I'd just like to know if it's working as intended, or if it's an unintentional feature.

_Just for posterity, I'm keeping the old, irrelevant part of the issue post here:_

> Would you consider support for a mod like Et Futurum which backports the status effect into 1.7.10?
> I know it might not be that common of a scenario, but it would be a really neat addition to the mod.
> 
> EDIT: I should have tested the Jump Boost thing before posting. I just assumed the feature wasn't present in the 1.7.10 version, but it seems to be, at least the base step-assist part. Still, Mine and Blade compatibility for shield parachuting would be nice.

> On the topic of features,

**Comment by SoraZodia** [comment]
> Perhaps you could backport the parachute feature and allow users to specify items which act as parachutes? I know I for one would love to have support for the Crystal Wing or Mine and Blade's shields, but then I'm not sure if M&B's shields are quite... parachute-y enough. You'd probably also need special code to support it's offhand feature, so that might end up being a no.  

For the offhand support, I could probably look into its code or ask its author about it. If there's an api I can use (and if I can figure out how to link it in Eclipse), then I would likely add it in.

Generally I like to focus on an single minecraft version, but I'll see about backporting the parachute feature 

>After a little experimentation, I seem to be throwing two arrows at once, rather than just one.

I thought I had fixed that... I'll take another look at it.

>There's also the issue of it not supporting modded arrow types, but I don't know if you can help that.

There's actually not much I can do about it, I would have to manually add support for them because Minecraft don't have an parent arrow class that I can take advantage of. And that's something I would rather not do.

>Also, I'm not sure if this is entirely intentional or even preventable, but if you mine Netherrack/Quartz slowly and carefully, the lava will disappear within seconds instead of spreading out. It's actually kinda neat to need to change up how I mine, and I've proven to myself that accidents still happen if you get careless. I'd just like to know if it's working as intended, or if it's an unintentional feature.

Yup, that's an intended behavior - I took advantage of how liquid behaves in Minecraft.

>I should have tested the Jump Boost thing before posting. I just assumed the feature wasn't present in the 1.7.10 version, but it seems to be, at least the base step-assist part.

~~1.7.10 should be able to grant additional step-assists based on your potion level. It's an recurring bug that been taunting me since I had started developing the mod.~~  
Scratch that, it's an derp in the config that I fixed later on in Minecraft 1.8.9. In the mod's config, change the upper limit for the step-assist to an really high number (like 255) and it should work as intended. If not, refer back to the scratched out sentence while I proceed to throw my computer out the window.

**Comment by DarianLStephens** [comment]
Well, it seems you're right about the step-assist, and it's nice to know about the liquid (Even if you did find it a bug, I would've asked that you keep it and brand it as a feature).
I have discovered what seems to be a new bug or oversight, though, and will post it as a new issue.

While I'm here, have you ~~looked into backporting the parachute feature, or~~ seen if you can add support for Mine and Blade's offhand?
(Sorry about the parachute thing; I hadn't checked the curseforge page in ages, and it just occurred to me that you might have updated the mod since I last downloaded it. That parachute thing is gonna be awesome!)

**Comment by SoraZodia** [comment]
I did a quick skim through the code, and it does looks like I can add support in for off hand. So I'll see if I can get that working.

**Comment by SoraZodia** [comment]
And I was not able to figure it out, I don't think I'll be able to fully add it in. Thanks for the idea though, I might give it another try in the future.

There is some support for offhand though. When you are dual-wielding, the tool in your right arm will place the block in the first or last slot of your hotbar.
